apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-http-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: go-http
  template:
    metadata:
      labels:
        app: go-http
    spec:
      containers:
        - name: go-http
          image: {{ .Values.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName }}
