apiVersion: v1
kind: ConfigMap
metadata:
  name: test-service-env
data:
  DB_HOST: "mysql-service"
  DB_USER: "root"
  DB_PASSWORD: "root123"
  DB_NAME: "test_db"
  DB_PORT: "3306"
  DB_DIALECT: "mysql"
