apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.image }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysqlRootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysqlDatabase }}
          ports:
            - containerPort: {{ .Values.containerPort }}