replicaCount: 3
image: go-http-server:1.1
containerPort: 8000
nodePort: 30080
resources:
  requests:
    cpu: "100m"
  limits:
    cpu: "500m"
config:
  DB_HOST: mysql-service
  DB_USER: root
  DB_PASSWORD: root123
  DB_NAME: test_db
  DB_PORT: "3306"
  DB_DIALECT: mysql
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50